# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06974fba32c95fd8b219602adcf2f346bfe2be4e5e831628e20c591686db251af2c79e7f3fd72d95d25ae7313bfdd9d0efe867781ec86820d337d53f3ec7d026

test:
  secret_key_base: 2a7fbebf6f3b53efb8e8a6b6c2d8146dbb2b3ed9be1b234fa87365ff61a9cb2d64a40897f4483e595c2b0acc3f7a0da324716735645663cd73c98978cc124acc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
